# Generated by Django 5.0.6 on 2024-06-24 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="FieldOfStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_number", models.PositiveIntegerField()),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100)),
                ("school", models.CharField(max_length=100)),
                ("field_of_study", models.CharField(max_length=50)),
                ("year", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="RepeatedCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(max_length=50)),
                ("course_name", models.CharField(max_length=50)),
                ("course_short", models.CharField(max_length=50)),
                (
                    "field_of_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.fieldofstudy",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="repeated_courses", to="students.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CurrentCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(max_length=50)),
                ("course_name", models.CharField(max_length=50)),
                ("course_short", models.CharField(max_length=50)),
                (
                    "field_of_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.fieldofstudy",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="current_courses", to="students.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TutorialGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "field_of_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.fieldofstudy",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="tutorial_groups", to="students.student"
                    ),
                ),
            ],
        ),
    ]
