# Generated by Django 5.0.6 on 2024-08-02 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="FieldOfStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_number", models.PositiveIntegerField(unique=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100)),
                ("school", models.CharField(max_length=100)),
                ("field_of_study", models.CharField(max_length=50)),
                ("year", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="CurrentCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(max_length=50)),
                ("course_name", models.CharField(max_length=50)),
                ("course_short", models.CharField(max_length=50)),
                (
                    "field_of_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.fieldofstudy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RepeatedCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(max_length=50)),
                ("course_name", models.CharField(max_length=50)),
                ("course_short", models.CharField(max_length=50)),
                (
                    "field_of_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.fieldofstudy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RepeatedCourseStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_carried", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.repeatedcourse",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="repeatedcourse",
            name="students",
            field=models.ManyToManyField(
                related_name="repeated_courses",
                through="students.RepeatedCourseStatus",
                to="students.student",
            ),
        ),
        migrations.CreateModel(
            name="CurrentCourseStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_carried", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.currentcourse",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="currentcourse",
            name="students",
            field=models.ManyToManyField(
                related_name="current_courses",
                through="students.CurrentCourseStatus",
                to="students.student",
            ),
        ),
        migrations.CreateModel(
            name="TutorialGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "field_of_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.fieldofstudy",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="tutorial_groups", to="students.student"
                    ),
                ),
            ],
        ),
    ]
