# Generated by Django 5.0.6 on 2024-08-12 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentcoursestatus',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_course_statuses', to='students.student'),
        ),
        migrations.AlterField(
            model_name='repeatedcoursestatus',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeated_course_statuses', to='students.student'),
        ),
    ]
